package com.sofans.entity.goods;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.sofans.entity.IBean;

/**
 * Goods generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "goods", catalog = "goods")
public class Goods implements IBean {

	private Integer id;
	private int goodsClassId;
	private String goodName;
	private String goodNumber;
	private String introduce;
	private int brand;
	private Float weight;
	private String image;
	private float marketPrice;
	private float memberPrice;
	private Short isHot;
	private Short isDiscount;
	private Short isNew;
	private Short isPefect;
	private Integer gsequence;
	private Integer stock;
	private Integer soldout;
	private Short status;
	private Date addData;

	public Goods() {
	}

	public Goods(int goodsClassId, String goodName, String goodNumber,
			String image, float marketPrice, float memberPrice, Short status, Date addData) {
		this.goodsClassId = goodsClassId;
		this.goodName = goodName;
		this.goodNumber = goodNumber;
		this.image = image;
		this.marketPrice = marketPrice;
		this.memberPrice = memberPrice;
		this.status = status;
		this.addData = addData;
	}

	public Goods(int goodsClassId, String goodName, String goodNumber,
			String introduce, int brand, Float weight, String image,
			float marketPrice, float memberPrice, Short isHot,
			Short isDiscount, Short isNew, Short isPefect, Integer gsequence,
			Integer stock, Integer soldout, Short status, Date addData) {
		this.goodsClassId = goodsClassId;
		this.goodName = goodName;
		this.goodNumber = goodNumber;
		this.introduce = introduce;
		this.brand = brand;
		this.weight = weight;
		this.image = image;
		this.marketPrice = marketPrice;
		this.memberPrice = memberPrice;
		this.isHot = isHot;
		this.isDiscount = isDiscount;
		this.isNew = isNew;
		this.isPefect = isPefect;
		this.gsequence = gsequence;
		this.stock = stock;
		this.soldout = soldout;
		this.status = status;
		this.addData = addData;
	}

	@Id
	@GenericGenerator(name="generator",strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "goods_class_id", nullable = false)
	public int getGoodsClassId() {
		return this.goodsClassId;
	}

	public void setGoodsClassId(int goodsClassId) {
		this.goodsClassId = goodsClassId;
	}

	@Column(name = "good_name", nullable = false, length = 50)
	public String getGoodName() {
		return this.goodName;
	}

	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}

	@Column(name = "good_number", nullable = false, length = 50)
	public String getGoodNumber() {
		return this.goodNumber;
	}

	public void setGoodNumber(String goodNumber) {
		this.goodNumber = goodNumber;
	}

	@Column(name = "introduce", length = 200)
	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	@Column(name = "brand", length = 100)
	public int getBrand() {
		return this.brand;
	}

	public void setBrand(int brand) {
		this.brand = brand;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "image", nullable = false, length = 150)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "market_price", nullable = false, precision = 12, scale = 0)
	public float getMarketPrice() {
		return this.marketPrice;
	}

	public void setMarketPrice(float marketPrice) {
		this.marketPrice = marketPrice;
	}

	@Column(name = "member_price", nullable = false, precision = 12, scale = 0)
	public float getMemberPrice() {
		return this.memberPrice;
	}

	public void setMemberPrice(float memberPrice) {
		this.memberPrice = memberPrice;
	}

	@Column(name = "is_hot")
	public Short getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Short isHot) {
		this.isHot = isHot;
	}

	@Column(name = "is_discount")
	public Short getIsDiscount() {
		return this.isDiscount;
	}

	public void setIsDiscount(Short isDiscount) {
		this.isDiscount = isDiscount;
	}

	@Column(name = "is_new")
	public Short getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Short isNew) {
		this.isNew = isNew;
	}

	@Column(name = "is_pefect")
	public Short getIsPefect() {
		return this.isPefect;
	}

	public void setIsPefect(Short isPefect) {
		this.isPefect = isPefect;
	}

	@Column(name = "gsequence")
	public Integer getGsequence() {
		return this.gsequence;
	}

	public void setGsequence(Integer gsequence) {
		this.gsequence = gsequence;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "soldout")
	public Integer getSoldout() {
		return this.soldout;
	}

	public void setSoldout(Integer soldout) {
		this.soldout = soldout;
	}
	@Column(name = "status")
	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_data", nullable = false, length = 19)
	public Date getAddData() {
		return this.addData;
	}

	public void setAddData(Date addData) {
		this.addData = addData;
	}

}
